### ISSUE TITLE
Failed to compile cmake with protobuf

### ISSUE THREAD

**Issue by Assassin-plus** [Ther-nullptr/Summertraining-homework#3]

**Comment by Assassin-plus** [comment]
按教程做下来正常，protoc命令也有反应
但是cmake时出现以下错误

CMake Error at CMakeLists.txt:3 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/dell/homework/CMakeFiles/CMakeOutput.log".
See also "/mnt/c/Users/dell/homework/CMakeFiles/CMakeError.log".

**Comment by Ther-nullptr** [comment]
你的protoc版本是多少

**Comment by Ther-nullptr** [comment]
```cmake
cmake_minimum_required(VERSION 3.5)

project(protobuf_homework)

find_package(Protobuf REQUIRED)

message("${PROJECT_SOURCE_DIR}")

set(PROTOBUF_LIBPROTOBUF protobuf::libprotobuf)

message("Protobuf_INCLUDE_DIRS:${Protobuf_INCLUDE_DIRS}")

set(SOURCES src/player.pb.cc src/main.cpp)

# TODO 4:include the head files and use .cpp to generate executable
add_executable(protobuf_homework ${SOURCES})
target_include_directories(protobuf_homework PUBLIC ${PROJECT_SOURCE_DIR}/include)

target_link_libraries(protobuf_homework ${PROTOBUF_LIBPROTOBUF})
```

**Comment by Ther-nullptr** [comment]
试试这个cmake，网上说可能和装了grpc有关 
https://stackoverflow.com/questions/68274203/could-not-find-a-package-configuration-file-provided-by-protobuf-with-any-of-t

**Comment by Assassin-plus** [comment]
> 你的protoc版本是多少
libprotoc 3.20.1，


> 试试这个cmake，网上说可能和装了grpc有关 https://stackoverflow.com/questions/68274203/could-not-find-a-package-configuration-file-provided-by-protobuf-with-any-of-t

用了这个以后cmake没问题了，make的时候有提示
This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.
应该要用哪个版本呢

**Comment by Assassin-plus** [comment]
尝试再用protoc编译了一下，成功了
